# Generated by Django 2.2.6 on 2020-02-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Electronic'), (1, 'Furniture'), (2, 'Major Appliance'), (3, 'Kitchen'), (4, 'Books'), (5, 'Motors')], default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('condition', models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Working')], default=4)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
