# Generated by Django 3.0 on 2020-04-01 14:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Electronic'), (1, 'Furniture'), (2, 'Major Appliance'), (3, 'Kitchen'), (4, 'Books'), (5, 'Motors'), (6, 'Music'), (7, 'Other')], default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('condition', models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True)),
                ('publish', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
