# Generated by Django 3.0.3 on 2020-02-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Working'), (1, 'Used - Like New'), (3, 'Used - working')], default=4),
        ),
    ]
