# Generated by Django 3.0.3 on 2020-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200227_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (4, 'Used - Not Working'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
