# Generated by Django 2.2.6 on 2020-02-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200202_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (1, 'Used - Like New'), (4, 'Used - Not Working'), (3, 'Used - working'), (2, 'Used - Good')], default=4),
        ),
    ]
