# Generated by Django 3.0 on 2020-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200401_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (0, 'Brand New'), (1, 'Used - Like New'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
