# Generated by Django 2.2.6 on 2019-11-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
