# Generated by Django 2.2.6 on 2020-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200202_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Working'), (1, 'Used - Like New'), (0, 'Brand New'), (2, 'Used - Good'), (3, 'Used - working')], default=4),
        ),
    ]
