# Generated by Django 3.0.3 on 2020-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200226_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Working')], default=4),
        ),
    ]
