# Generated by Django 3.0.3 on 2020-02-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200226_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (3, 'Used - working'), (4, 'Used - Not Working'), (1, 'Used - Like New'), (2, 'Used - Good')], default=4),
        ),
    ]
