# Generated by Django 3.0.3 on 2020-04-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200403_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
