# Generated by Django 2.2.6 on 2020-02-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200202_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Working'), (3, 'Used - working')], default=4),
        ),
    ]
