# Generated by Django 3.0.5 on 2020-04-15 20:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200413_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
