# Generated by Django 3.0.3 on 2020-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200301_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Working'), (3, 'Used - working'), (1, 'Used - Like New'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
