# Generated by Django 2.2.6 on 2020-02-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200202_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (3, 'Used - working'), (1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Working')], default=4),
        ),
    ]
