# Generated by Django 3.0.5 on 2020-04-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200415_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
