# Generated by Django 2.2.6 on 2020-02-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200201_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (3, 'Used - working'), (4, 'Used - Not Working'), (0, 'Brand New'), (1, 'Used - Like New')], default=4),
        ),
    ]
