# Generated by Django 3.0.5 on 2020-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200415_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
