# Generated by Django 2.2.6 on 2019-12-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191201_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (4, 'Used - Not Working'), (3, 'Used - working'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
