# Generated by Django 2.2.6 on 2019-12-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (4, 'Used - Not Working'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
