# Generated by Django 3.0.3 on 2020-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200301_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - working'), (0, 'Brand New'), (2, 'Used - Good'), (1, 'Used - Like New'), (4, 'Used - Not Working')], default=4),
        ),
    ]
