# Generated by Django 2.2.6 on 2019-12-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20191201_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - working'), (1, 'Used - Like New'), (0, 'Brand New'), (2, 'Used - Good'), (4, 'Used - Not Working')], default=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
