# Generated by Django 3.0.5 on 2020-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200419_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (1, 'Used - Like New'), (2, 'Used - Good')], default=4),
        ),
    ]
