# Generated by Django 2.2.6 on 2019-12-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20191201_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (4, 'Used - Not Working'), (0, 'Brand New'), (2, 'Used - Good')], default=4),
        ),
    ]
