# Generated by Django 3.0.5 on 2020-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200419_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
