# Generated by Django 3.0.3 on 2020-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200301_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - working'), (0, 'Brand New'), (4, 'Used - Not Working'), (2, 'Used - Good')], default=4),
        ),
    ]
