# Generated by Django 3.0.3 on 2020-03-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200301_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Electronic'), (1, 'Furniture'), (2, 'Major Appliance'), (3, 'Kitchen'), (4, 'Books'), (5, 'Motors'), (6, 'Music'), (7, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (2, 'Used - Good')], default=4),
        ),
    ]
