# Generated by Django 3.0.5 on 2020-04-20 09:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200420_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (2, 'Used - Good')], default=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
