# Generated by Django 2.2.6 on 2019-12-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20191203_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (0, 'Brand New'), (3, 'Used - working'), (4, 'Used - Not Working'), (1, 'Used - Like New')], default=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='images/no-image-available-icon-6.jpg', upload_to='images/'),
        ),
    ]
