# Generated by Django 3.0.3 on 2020-03-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20200301_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (2, 'Used - Good'), (1, 'Used - Like New')], default=4),
        ),
    ]
