# Generated by Django 3.0.5 on 2020-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200420_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (2, 'Used - Good')], default=4),
        ),
    ]
