# Generated by Django 3.0 on 2020-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200329_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (0, 'Brand New')], default=4),
        ),
    ]
