# Generated by Django 2.2.6 on 2019-12-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20191203_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - working'), (4, 'Used - Not Working')], default=4),
        ),
    ]
