# Generated by Django 3.0 on 2020-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200329_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New')], default=4),
        ),
    ]
