# Generated by Django 2.2.6 on 2019-12-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20191204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Working'), (3, 'Used - working'), (2, 'Used - Good')], default=4),
        ),
    ]
