# Generated by Django 3.0 on 2020-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200329_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable'), (1, 'Used - Like New'), (2, 'Used - Good'), (0, 'Brand New')], default=4),
        ),
    ]
