# Generated by Django 3.0.5 on 2020-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200607_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Usable'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
