# Generated by Django 3.0.5 on 2020-06-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20200607_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (4, 'Used - Not Usable'), (1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (0, 'Brand New')], default=4),
        ),
    ]
