# Generated by Django 2.2.7 on 2019-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20191205_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (3, 'Used - working'), (0, 'Brand New'), (4, 'Used - Not Working')], default=4),
        ),
    ]
