# Generated by Django 2.2.6 on 2020-02-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20191206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (4, 'Used - Not Working'), (1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - working')], default=4),
        ),
    ]
