# Generated by Django 3.0 on 2020-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200330_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (1, 'Used - Like New'), (0, 'Brand New'), (3, 'Used - Poor Condidtion'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
