# Generated by Django 3.0 on 2020-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20200330_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (2, 'Used - Good'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
