# Generated by Django 3.0 on 2020-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20200330_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (4, 'Used - Not Usable'), (1, 'Used - Like New'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
