# Generated by Django 3.0 on 2020-03-30 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20200330_1532'),
        ('posts', '0023_auto_20200330_1811'),
    ]

    operations = [
    ]
