# Generated by Django 3.0 on 2020-03-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20200330_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (0, 'Brand New'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
