# Generated by Django 3.0 on 2020-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20200330_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (2, 'Used - Good'), (0, 'Brand New'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
