# Generated by Django 3.0.3 on 2020-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.IntegerField(choices=[(0, 'Undergraduate Student'), (1, 'Graduate Student'), (2, 'Faculty Member'), (3, 'Staff')], default=4),
        ),
    ]
