# Generated by Django 3.0.5 on 2020-04-15 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200329_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16)]),
        ),
    ]
