# Generated by Django 3.0.3 on 2020-03-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
