# Generated by Django 3.0.5 on 2020-04-15 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200415_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
