# Generated by Django 3.0.5 on 2020-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200415_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='street_address_1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address_2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
